spring.application.name=ntalk

# =============================================
# Lightsail PostgreSQL 연결 설정
# =============================================
spring.datasource.url=jdbc:postgresql://ls-5f64aa7ed07442b10117b0598708e167f910fb43.cx0kqa40mod9.ap-northeast-2.rds.amazonaws.com:5432/postgres?sslmode=prefer
spring.datasource.username=dbmasteruser
spring.datasource.password=dygksqhrdma3wkd16wjf!!
spring.datasource.driver-class-name=org.postgresql.Driver
# MyBatis Settings
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.ntalk.choi.domain
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

# HikariCP 커넥션 풀 설정
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
