spring.application.name=ntalk

# =============================================
# Supabase PostgreSQL (nproject2) 연결 설정
# =============================================
#spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
#spring.datasource.username=postgres.xedelkathoiufubtupat
#spring.datasource.password=nadaj40!!
#spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?prepareThreshold=0&sslmode=require
spring.datasource.username=postgres.xedelkathoiufubtupat
spring.datasource.password=nadaj40!!
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis Settings
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.ntalk.choi.domain
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

# HikariCP 커넥션 풀 설정
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
